// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nordlys.Game.Habbos;

namespace Nordlys.Migrations
{
    [DbContext(typeof(HabboDbContext))]
    [Migration("20200205184749_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Nordlys.Game.Habbos.Habbo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AchievementPoints")
                        .HasColumnName("achievement_points")
                        .HasColumnType("int");

                    b.Property<string>("AuthenticationTicket")
                        .HasColumnName("authentication_ticket")
                        .HasColumnType("varchar(70) CHARACTER SET utf8mb4")
                        .HasMaxLength(70);

                    b.Property<int>("Coins")
                        .HasColumnName("coins")
                        .HasColumnType("int");

                    b.Property<string>("DateOfBirth")
                        .HasColumnName("date_of_birth")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Email")
                        .HasColumnName("email")
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Figure")
                        .HasColumnName("figure")
                        .HasColumnType("varchar(90) CHARACTER SET utf8mb4")
                        .HasMaxLength(90);

                    b.Property<string>("Gender")
                        .HasColumnName("gender")
                        .HasColumnType("varchar(1) CHARACTER SET utf8mb4")
                        .HasMaxLength(1);

                    b.Property<string>("Motto")
                        .HasColumnName("motto")
                        .HasColumnType("varchar(40) CHARACTER SET utf8mb4")
                        .HasMaxLength(40);

                    b.Property<sbyte>("Rank")
                        .HasColumnName("rank")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("SignedUp")
                        .HasColumnName("signed_up")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .HasColumnName("name")
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
